//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Cần thiết lập")]
        [DisplayName("Họ và tên")]
        public string Name { get; set; }

        [DisplayName("Số điện thoại")]
        public string Phone { get; set; }

        [DisplayName("Địa chỉ")]
        public string Address { get; set; }

        [DisplayName("Lương")]
        public string Salary { get; set; }

        public byte[] Avatar { get; set; }

        [Required(ErrorMessage = "Cần thiết lập")]
        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> DoB { get; set; }

        [Required(ErrorMessage = "Cần thiết lập")]
        [DisplayName("Giới tính")]
        public Nullable<bool> Gender { get; set; }
    }
}
